spring:
  profiles:
    active: development

---
spring:
  profiles: development

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /config-service/info
    homePageUrlPath: /config-service/
    healthCheckUrlPath: /config-service/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled:true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

       
          
---
spring:
  profiles: docker

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /config-service/info
    homePageUrlPath: /config-service/
    healthCheckUrlPath: /config-service/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled:true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/

        
