server:
  port: 8888
  contextPath: /config-service
  

eureka:
  instance:
    hostname: config-service
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /config-service/info
    homePageUrlPath: /config-service/
    healthCheckUrlPath: /config-service/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled:true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: hhttps://github.com/jmg2014/spring-boot-microservice-config.git
