spring:
  profiles:
    active: development

info:
  component: Employee service    
---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://localhost:3306/airlanedb?useSSL=true
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop    
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:   
        dialect: org.hibernate.dialect.MySQL5Dialect


eureka:
  instance:
    prefer-ip-address: true
    statusPageUrlPath: /airlane-employee-service/info
    healthCheckUrlPath: /airlane-aircremployee-service/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled:true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/airlanedb?useSSL=true
    username: root
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop    
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:   
        dialect: org.hibernate.dialect.MySQL5Dialect
    
eureka:
  instance:
    prefer-ip-address: true
    statusPageUrlPath: /airlane-employee-service/info
    healthCheckUrlPath: /airlane-employee-service/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled:true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/   
    

