spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: airlane-edge-service

zuul:
    ignoredServices: '*'
    routes:
      airlane-web:
        path: /airlane-web/**
        serviceId: airlane-web        
        stripPrefix: false 
      airlane-employee-service:
        path: /v1/employee-service/**
        serviceId: airlane-employee-service        
        stripPrefix: false 
     
info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
         
eureka:
  instance:
      prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled:true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
---
spring:
  profiles: docker
  application:
    name: airlane-edge-service

zuul:
    ignoredServices: '*'
    routes:
      airlane-web:
        path: /airlane-web/**
        serviceId: airlane-web        
        stripPrefix: false
      airlane-employee-service:
        path: /v1/employee-service/**
        serviceId: airlane-employee-service        
        stripPrefix: false  
     
info:
  component: Zuul Server
  
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
         
eureka:
  instance:
      prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled:true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/      
          