spring:
  profiles:
    active: development
---
spring:
  profiles: development

eureka:
  instance:
    prefer-ip-address: true
    statusPageUrlPath: /airlane-admin/info
    healthCheckUrlPath: /airlane-admin/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled:true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false   
  
---
spring:
  profiles: docker
    
eureka:
  instance:
    prefer-ip-address: true
    statusPageUrlPath: /airlane-admin/info
    healthCheckUrlPath: /airlane-admin/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled:true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/   
management:
  security:
    enabled: false 

