spring:
  profiles:
    active: development

info:
  component: Web 
  app:
    name: Airlane-Web
    version: 1.0.0
    description: Web
---
spring:
  profiles: development

eureka:
  instance:
    prefer-ip-address: true
    statusPageUrlPath: /airlane-web/info
    homePageUrlPath: /airlane-web/
    healthCheckUrlPath: /airlane-web/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled:true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false

    

    
---
spring:
  profiles: docker
    
eureka:
  instance:
    prefer-ip-address: true
    statusPageUrlPath: /airlane-web/info
    homePageUrlPath: /airlane-web/
    healthCheckUrlPath: /airlane-web/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled:true
    serviceUrl:
      defaultZone: http://192.168.99.100:8761/eureka/         
management:
  security:
    enabled: false     

