server:
  port: 8080
  context-path: /airlane-web

eureka:
  instance:
    hostname: airlane-web
    statusPageUrlPath: /airlane-web/info
    healthCheckUrlPath: /airlane-web/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled:true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

